### ISSUE TITLE
Android back button crash

### ISSUE THREAD

**Issue by no-dap** [iamport/iamport-capacitor#13]
Android IamportActivity에서 webview가 생성된 후에 back button press 시 handleOnActivityResult로 null intent가 전달되면서  
아래와 같은 에러가 발생합니다.  
```
java.lang.NullPointerException: Attempt to invoke virtual method 'android.os.Bundle android.content.Intent.getExtras()' on a null object reference
        at kr.iamport.capacitor.IamportCapacitor.handleOnActivityResult(IamportCapacitor.java:45)
        at com.getcapacitor.Bridge.onActivityResult(Bridge.java:776)
        at com.getcapacitor.BridgeActivity.onActivityResult(BridgeActivity.java:214)
        at android.app.Activity.dispatchActivityResult(Activity.java:8110)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4838)
```

해당 부분 handling code를 #12 로 PR을 생성해두었습니다.

**Comment by no-dap** [comment]
duplicate of #11
