### ISSUE TITLE
java.lang.ClassNotFoundException: android.support.design.widget.CoordinatorLayout

### ISSUE THREAD

**Issue by pjc0247** [iamport/iamport-capacitor#52]
최신 버전의 capacitor 프로젝트를 생성해서 연동해보시면 아래와 같은 에러가 발생합니다.

`bridge_layout_main.xml`의 내용을 
`androidx.coordinatorlayout.widget.CoordinatorLayout`
로 수정하여 임시 해결하였습니다.

```
2021-11-08 15:22:04.862 15747-15747/? E/o.ionic.starte: Invalid ID 0x00000000.
2021-11-08 15:22:04.928 15747-15747/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: io.ionic.starter, PID: 15747
    java.lang.RuntimeException: Unable to start activity ComponentInfo{io.ionic.starter/io.ionic.starter.MainActivity}: android.view.InflateException: Binary XML file line #8 in io.ionic.starter:layout/bridge_layout_main: Binary XML file line #8 in io.ionic.starter:layout/bridge_layout_main: Error inflating class android.support.design.widget.CoordinatorLayout
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3840)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4016)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2325)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:247)
        at android.app.ActivityThread.main(ActivityThread.java:8656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
     Caused by: android.view.InflateException: Binary XML file line #8 in io.ionic.starter:layout/bridge_layout_main: Binary XML file line #8 in io.ionic.starter:layout/bridge_layout_main: Error inflating class android.support.design.widget.CoordinatorLayout
     Caused by: android.view.InflateException: Binary XML file line #8 in io.ionic.starter:layout/bridge_layout_main: Error inflating class android.support.design.widget.CoordinatorLayout
     Caused by: java.lang.ClassNotFoundException: android.support.design.widget.CoordinatorLayout
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:454)
        at android.view.LayoutInflater.createView(LayoutInflater.java:813)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1004)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:959)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:657)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:532)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:479)
        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:696)
        at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:170)
        at com.getcapacitor.BridgeActivity.onCreate(BridgeActivity.java:28)
        at io.ionic.starter.MainActivity.onCreate(MainActivity.java:13)
        at android.app.Activity.performCreate(Activity.java:8215)
        at android.app.Activity.performCreate(Activity.java:8199)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3813)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4016)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2325)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:247)
        at android.app.ActivityThread.main(ActivityThread.java:8656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
2021-11-08 15:22:04.928 15747-15747/? E/AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.design.widget.CoordinatorLayout" on path: DexPathList[[zip file "/data/app/~~Q357JPwPlfn0L7quGL26tQ==/io.ionic.starter-zGkr7HEjv2IYPT-1e9T-lw==/base.apk"],nativeLibraryDirectories=[/data/app/~~Q357JPwPlfn0L7quGL26tQ==/io.ionic.starter-zGkr7HEjv2IYPT-1e9T-lw==/lib/arm64, /system/lib64, /system/system_ext/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        	... 27 more

```

**Comment by kjh5833** [comment]
안녕하세요. 아임포트 기술지원팀입니다.

v1.0.0 으로 확인 부탁드립니다.

감사합니다.
